name: Test
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov coveralls autopep8 pyflakes pylint
    - name: Run autopep8
      run: |
        autopep8 --diff --aggressive --aggressive  --exclude='HW2/test_*.py' HW2/*.py
    - name: Run pyflakes
      run: |
        pyflakes HW2/*.py
    - name: Run pylint
      run: |
        pylint HW2/*.py
    - name: Test with pytest
      run: |
        pytest --cov=./; echo
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
