name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test_myfile.py --doctest-modules --cov=myfile.py --cov-report=xml:/workspaces/HW1/ --cov-report=html
